import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Topo from "@/components/topo/topo";
import SlideBar from "@/components/slideBar/slideBar";
import Categoria from "@/components/section-categoria/categoria";
import Bombando from "@/components/section-bombando/bombando";
import colecao from "@/colecao/colecao";
import Alerta from "@/components/alerta/alerta";
import Facilidades from "@/components/sectionFacilidades/facilidades";
import React , {useState , useRef , useEffect} from "react";









export default function Home() {


  const [inputTx , setInputTx] = useState('')
  const [array , setArray] = useState(colecao)
  const [alertaStyle , setAlertaStyle] = useState(styles.alertaOff)

  



  function clickBusca(){

    
    const bomb = window.document.getElementById('idbombando')


    let filtrado = (colecao.filter((colecao)=> 
      
            colecao.titulo.toLowerCase().includes(inputTx.toLowerCase())||
            colecao.paragrafo.toLowerCase().includes(inputTx.toLowerCase())
           
        ))

    
   

      if(filtrado.length === 0 || inputTx.length === 0){

          setAlertaStyle(styles.alertaOn)
          setInputTx('')

      }else{

        bomb.scrollIntoView({behavior:'smooth'})
        setArray(filtrado)
        setInputTx('')
      }
    
    
  }


    
 
  // function buscarTexto(tx){

  //   let filtrado = (colecao.filter((colecao)=> 
      
  //       colecao.titulo.toLowerCase().includes(tx.toLowerCase())||
  //       colecao.paragrafo.toLowerCase().includes(tx.toLowerCase())
       
  //   ))
    

    

  //       setInputTx(setArray(filtrado))
    


  //     if(filtrado.length === 0){

  //       setAlertaStyle(styles.alertaOn)
        
  //       setTimeout(()=>{

  //           setAlertaStyle(styles.alertaOff)
  //       },3000)   

  //     }else{

  //       setAlertaStyle(styles.alertaOff)
        
  //     }

   
  // }

  

  function Change(ev){

    
    // buscarTexto(ev.target.value)

    setInputTx(ev.target.value)
    
      
    }

   
  

    function buscaProdutos(prod){

      const elemento2 = window.document.getElementById('idprodutos')

      elemento2.scrollIntoView({behavior:'smooth'})

      let filtro = colecao.filter((colecao)=>
      
          colecao.titulo === prod
      
      )
      
      setArray(filtro)

    }

     
      function AlertaFechar(){

          setAlertaStyle(styles.alertaOff)
      }



      function clickTopo(){

        const topo = document.getElementById('idtopo')

            topo.scrollIntoView({behavior:'smooth'})

           setTimeout(()=>{

              setArray(colecao)
            }, 1000)


            

    }
  
  

  return (
    <>
      <Head>
        <title>Meteora</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />

      </Head>

      <header>

        <Topo 
        
        clickBusca={clickBusca}
        inputTx={inputTx}
        change={Change}
        
        />

        
      </header>

     <main>

      <SlideBar/>
      <Categoria
      
      clickBusca={clickBusca}
      buscaProdutos={buscaProdutos}
      
      />

      <Bombando
      
      array={array}
      clickTopo={clickTopo}
     
      
      />

      <Alerta
      
      alertaStyle={alertaStyle}
      AlertaFechar={AlertaFechar}
    
      />

      <Facilidades/>
    
     </main>
    </>
  );
}
